### PR TITLE
 Adding Türkçe(Turkish) translation 

### PR DESCRIPTION
**Pull request by halak0013**
As-salamu Alaykum,
I add Türkçe(Turkish) translation on app inshAllah.

### CODE REVIEW

**Comment by halak0013** [comment]
Also I have small question. In our country our Quran words is a little different and its style and font different. I am developing a app for this situations. Can you add this future this app or can i try to add [repo](https://github.com/halak0013/Holy_Quran)
resim

**Comment by 0xzer0x** [comment]
Walaikum Assalam,
Jazakallah khair for taking the time to help in translating the application. I greatly appreciate it.

I would suggest waiting until the next merge with the main branch so the translation is up-to-date with the latest feature since the translation will be anyways a part of the upcoming release, which will be within a month inshallah.

For the mean time, I have cleaned up the `qc_template.ts` file as it had a few redundant lines to make the translation process easier.

**Comment by 0xzer0x** [comment]
As-salamu Alaykum,
Kindly checkout [this wiki page](https://github.com/0xzer0x/quran-companion/wiki/Contributing-Translations) for the new translation process. It should make it easier to keep up with new features and make the translation process easier on the long run. Sorry for any inconveniences and thanks for your patience.

**Comment by 0xzer0x** [comment]
As for the points mentioned concerning the Quran fonts. Unfortunately, adding the fonts mentioned to display the Quran page is not possible since the content does not align well when formatted to look like the mushaf page (e.g. page 5 in screenshot)

page

However, its still possible to use the fonts mentioned in the verse-by-verse tab and other places where page-like formatting is not required. I will take a look into implementing it in future releases inshallah.

Thanks

**Comment by halak0013** [comment]
resim
Actually, what I mean is not directly related to fonts.  While the Quran is being read in our country, many people do not know when and where the movements will come.
{وَبَشِّرِ ٱلَّذِينَ ءَامَنُواْ وَعَمِلُواْ ٱلصَّٰلِحَٰتِ أَنَّ لَهُمۡ جَنَّٰتٖ تَجۡرِي مِن تَحۡتِهَا ٱلۡأَنۡهَٰرُۖ كُلَّمَا رُزِقُواْ مِنۡهَا مِن ثَمَرَةٖ رِّزۡقٗا قَالُواْ هَٰذَا ٱلَّذِي رُزِقۡنَا مِن قَبۡلُۖ وَأُتُواْ بِهِۦ مُتَشَٰبِهٗاۖ وَلَهُمۡ فِيهَآ أَزۡوَٰجٞ مُّطَهَّرَةٞۖ وَهُمۡ فِيهَا خَٰلِدُونَ} [Al-Baqarah:25]

مِن for example we dont know how is it read  

مِن -> مِنَ or مِنُ or مِنِ or مِنْ  (i know its mean is 'from' and its correct form is مِنْ )

**Comment by 0xzer0x** [comment]
Thanks for the clarification. This means that the Quran db files need to be updated with the text containing the mentioned symbols in addition to adding a font that recognizes and renders the symbols. I tested it with the official [KFQPC Unicode Uthmanic Font](https://qurancomplex.gov.sa/en/techquran/dev/) and it produced the required text with the additional symbols. Will be working on adding it in the 1.2.1 release inshallah.

Will be closing this issue now since all translation contributions are hosted at the [crowdin](https://crowdin.com/project/quran-companion) platform from now on, so no need for manual pull requests.

**Comment by halak0013** [comment]
Thanks for the feedback.  I added the translations via [crowdin](https://crowdin.com/project/quran-companion).

**Pull request closed without merging**
